server:
  port: 80
  servlet:
    context-path: /




spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/code_gen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: gfp_gceb
#    password: Ms563dev#gceb121
    #oracle配置
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.10.10:1521:helowin
#    username: renren
#    password: 123456
    #SQLServer配置
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_security
#    username: sa
#    password: 123456
    #PostgreSQL配置
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.10.10:5432/renren_security
#    username: postgres
#    password: 123456
    # java-bean配置方式
  datasource:
    default:
      url: jdbc:mysql://localhost:3306/code_gen?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      maxActive: 20
      initialSize: 5
      testWhileIdle: true
      testOnReturn: true
      testOnBorrow: true
      timeBetweenEvictionRunsMillis: 5000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      minIdle: 3
      poolPreparedStatements: true
      logAbandoned: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      filters: stat,wall



mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
renren:
  database: mysql